name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12  # Use the installed Python version on your server

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Deploy only after tests pass

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.DEPLOY_SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to AWS EC2
      run: |
        ssh ubuntu@${{ secrets.DEPLOY_SERVER_IP }} << 'EOF'
          cd /path/to/your/app
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          systemctl restart your-app-service  # Restart your application
        EOF

    - name: Notify Deployment Status
      run: echo "Deployment to AWS EC2 completed successfully!"
