name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensures deployment happens only if tests pass
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DEPLOY_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to AWS EC2 and Restart Service
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.DEPLOY_SERVER_IP }} << 'EOF'
            cd /HNG-fastapi-books
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt

            # Restart the systemd service
            sudo systemctl daemon-reload
            sudo systemctl restart fastapi
            sudo systemctl status fastapi --no-pager

            # Check logs to ensure it started correctly
            sudo journalctl -u fastapi --no-pager --lines=20
          EOF

      - name: Notify Deployment Status
        run: echo "Deployment to AWS EC2 completed successfully!"
